version: "3"

tasks:
  # ---------------------------------------------------------------------------- #
  #                                    Upgrade                                   #
  # ---------------------------------------------------------------------------- #

  upgrade:
    cmds:
      - task: prompt-"Starting upgrades..."
      - task: prompt-"Linting..."
      - task: lints
      - task: prompt-"Upgrading Go"
      - task: upgrades-go
      - task: prompt-"Upgrading Bun"
      - task: upgrade-bun
      - task: prompt-"Upgrading Tooling"
      - task: install-tooling
      - task: prompt-"Upgrading Workflow"
      - task: upgrade-workflow
      - task: prompt-"Linting..."
      - task: lints
      - task: prompt-"Testing..."
      - task: tests-unit
      - task: prompt-"Committing upgrades"
      - git add . --update
      - 'git commit -m "chore(deps): upgrade"'
      - task: prompt-"Upgrade completed!"
