name: CI

on:
  push:
    branches: [main, ci/**]
  pull_request:
    branches: [main]

jobs:
  Scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Secret
        run: task scan-secrets-local

      - name: Vulnerability
        run: task scan-vulns-local

      - name: Misconfiguration
        run: task scan-misconfigs-local

  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: task lint-check

  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Unit
        run: task test-units
