name: CI

on:
  push:
    branches: [main, ci/**]
  pull_request:
    branches: [main]

jobs:
  Sentinel:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Scan
        run: |
          task scan-secrets-local
          task scan-vulns-local
          task scan-misconfigs-local

      - name: Lint
        run: task lints-check

      - name: Test
        run: task tests-flaky

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Test Reports
          path: |
            ./*/test/report
            !./vendor
            !./node_modules
            !./dist
          retention-days: 30
